Changed build number so it is more obvious what date it corresponds to
arras-energy/gridlabd-old pull request #121
Opened 2019-01-22 04:41 UTC by dchassin

This PR addresses issue #116.

## Current issues
None

## Code changes
Altered the method of calculating the build number.

## Documentation changes
None

## Test and Validation Notes
The command 
~~~
gridlabd --version
~~~
should report a build number in the form YYMMDD.

2019-02-08 22:56 UTC, aivanova5 requested changes
Docker system returns version on this branch as : 4.0.0-0
Further changes required.

2019-02-09 20:10 UTC, dchassin commented
The problem is the version of git on docker can be older and doesn't support the format string.  The problem was fixed by using a different command, e.g., `git log --max-count=1 --pretty=format:"%ai" | cut -c3,4,6,7,9,10`.

2019-02-10 00:52 UTC, aivanova5 approved these changes

2019-02-10 00:53 UTC, aivanova5 commented
It is now working -  with validation at 100%

2019-02-10 00:53 UTC, merged