Add support for influxdb
arras-energy/gridlabd-old pull request #526
Opened 2020-01-25 00:50 UTC by dchassin

This PR addresses issue #525.

## Current issues
1. Only HTTP is supported
2. Not certain how authentication should be done

## Code changes
- [X] Create module
- [ ] Create database class
- [ ] Create player class
- [ ] Create recorder class
- [ ] Create collector class

## Documentation changes
TODO

## Test and Validation Notes
- [ ] Create database connection test
- [ ] Create player test
- [ ] Create recorder test
- [ ] Create collector test

2020-02-18 22:09 UTC, dchassin commented
@aivanova5, do you know why the docker test details leads to 404?

2020-02-27 16:57 UTC, aivanova5 commented
Should this read me http://docs-dev.gridlabd.us/_page.html?&doc=/Module/Influxdb.md say 
`module influxdb` instead of `module database`?

2020-02-27 19:37 UTC, aivanova5 requested changes
When running this: https://github.com/slacgismo/gridlabd_virtual_islanding/tree/influxdb_test 
a segmentation fault occurs. Weirdly, commenting out the line "tags" in the recorder doesn't cause a Set fault.

2020-02-28 19:08 UTC, aivanova5 approved these changes

2020-02-28 19:10 UTC, merged